# Generated by Django 6.1.1 on 2026-09-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_clase_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='color',
            field=models.CharField(default='a103fc', max_length=20),
        ),
        migrations.AddField(
            model_name='clase',
            name='enfoque',
            field=models.CharField(default='Core', max_length=50),
        ),
        migrations.AddField(
            model_name='reserva',
            name='lesion',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha',
            field=models.CharField(max_length=20),
        ),
    ]
