# Generated by Django 6.1.1 on 2026-09-20 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_clase_color_clase_enfoque_reserva_lesion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
