# Generated by Django 6.1.1 on 2026-09-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_clase_hora_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='fecha_completa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
